name: AWS oidc workflow
on:
  push:
    branches:
    - main
env:
  BUCKET_NAME : "ddl.tf"
  AWS_REGION : "us-east-1"
# permission can be added at job level or workflow level    
permissions:
      id-token: write
      contents: read    # This is required for actions/checkout
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::368752026550:role/s3oidc
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      # Upload a file to AWS s3
      - name:  sync python to s3
        run: |
           aws s3 sync ./RDS/terraform postgres cluster script/main.tf s3://${{ env.BUCKET_NAME }}/
