name: AWS oidc workflow
on:
  push:
    branches:
    - main
env:
  BUCKET_NAME : "ps360dev2"
  AWS_REGION : "us-west-2"
# permission can be added at job level or workflow level    
permissions:
      id-token: write
      contents: read    # This is required for actions/checkout
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v1
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::368752026550:role/s3oidc
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Verify credentials
        run: |
          aws sts get-caller-identity
          
      # Upload a file to AWS s3
      - name:  cp python to s3
        run: |
          aws s3 cp ./RDS s3://${{ env.BUCKET_NAME }}/
